unless window.terraformScriptCoffeeInfoDisplayed?
  console.log "hello world from sample terraform coffee script", ctx
  window.terraformScriptCoffeeInfoDisplayed = yes

stage = $ '#stage'
stage.append "Some addendum generated by coffee script"